# Generated by Django 3.2.3 on 2021-05-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='es_aceptada',
            field=models.BooleanField(default=False, help_text='indica si la orden está aceptada por bodega', verbose_name='aceptada'),
        ),
    ]
