# Generated by Django 3.2.3 on 2021-06-22 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_orden_es_aceptada'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCasaCentral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_orden', models.DateTimeField(auto_now_add=True)),
                ('es_entregado', models.BooleanField(default=False)),
                ('responsable', models.CharField(help_text='requerido', max_length=100, verbose_name='solicitante de pedido')),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.producto')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.tienda')),
            ],
            options={
                'verbose_name': 'Orden de pedido',
                'verbose_name_plural': 'Ordenes de pedido',
            },
        ),
    ]
