# Generated by Django 3.2.3 on 2021-07-03 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_pedidocasacentral'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidocasacentral',
            options={'verbose_name': 'Pedido Casa Central', 'verbose_name_plural': 'Pedidos Casa Central'},
        ),
    ]
