# Generated by Django 3.2 on 2021-06-17 03:40

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(help_text='Campo requerido y único', max_length=200, unique=True, verbose_name='Nombre de Categoría')),
                ('is_active', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='casa_central.categoria')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Requerido', max_length=100, verbose_name='Tienda')),
                ('direccion', models.CharField(help_text=' Direccion de tienda solicitante', max_length=200, verbose_name='Direccion')),
                ('ciudad', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Requerido', max_length=255, verbose_name='nombre')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('codigo_producto', models.CharField(help_text='Requerido', max_length=50, unique=True, verbose_name='Codigo de producto')),
                ('sku', models.CharField(help_text='Requerido', max_length=50, unique=True, verbose_name='SKU')),
                ('descripcion', models.TextField(blank=True, help_text='Agregar descripción', verbose_name='descripción')),
                ('precio', models.PositiveIntegerField(verbose_name='precio')),
                ('es_activo', models.BooleanField(default=True, help_text='Desactiva producto de ser necesario', verbose_name='Producto activo')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='casa_central.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='OrdenPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_orden', models.DateTimeField(auto_now_add=True)),
                ('es_entregado', models.BooleanField(default=False)),
                ('responsable', models.CharField(help_text='requerido', max_length=100, verbose_name='solicitante de pedido')),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casa_central.producto')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casa_central.tienda')),
            ],
            options={
                'verbose_name': 'Orden de pedido',
                'verbose_name_plural': 'Ordenes de pedido',
            },
        ),
    ]
