# Generated by Django 3.2.3 on 2021-07-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='descripcion',
            field=models.CharField(default='', max_length=50),
        ),
    ]
