# Generated by Django 3.2.3 on 2021-07-04 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_moneda_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.tienda'),
        ),
    ]
